"""Apply explicit style changes to recognized slides without rebuilding their content."""
import re

from googleapiclient.errors import HttpError

from .slides import rgb
from .layouts import color_role, is_decoration
from . import gradients

BACKGROUND_FIELDS = ('background', 'gradient', 'gradient_color')


def inspect_slide(page):
    # Reuse the conservative text checks; never flatten custom or mixed text.
    from .editing import normalize_element

    slide_id = page['objectId']
    match = re.fullmatch(r'mvp_slide_(\d+)', slide_id)
    reasons, texts = [], []
    band = None
    gradient = None
    if not match:
        reasons.append('Only slides generated by this tool support styling.')
    suffix = match[1] if match else None
    elements = page.get('pageElements', [])
    for element in elements:
        element_id = element['objectId']
        data = gradients.inspect(element, suffix)
        if data is not None and suffix != '0':
            gradient = data
            continue
        if is_decoration(element, suffix):
            continue
        if suffix == '0' and element_id == 'mvp_cover_image' and 'image' in element:
            continue
        if (suffix == '0' and element_id == 'mvp_cover_band'
                and element.get('shape', {}).get('shapeType') == 'TEXT_BOX'
                and all('autoText' not in entry and not entry.get('textRun', {}).get('content', '').strip()
                        for entry in element['shape'].get('text', {}).get('textElements', []))):
            band = element
            continue
        normalized = normalize_element(element)
        if normalized['editable'] and element_id.rsplit('_', 1)[-1] == suffix:
            texts.append(element)
        else:
            reasons.append(f'{element_id}: unsupported element; preserved unchanged.')
    if not texts:
        reasons.append('No supported text boxes.')
    if suffix == '0' and band is None:
        reasons.append('The original empty cover title band is missing or modified.')
    if gradient:
        try:
            solid = page.get('pageProperties', {}).get('pageBackgroundFill', {}).get('solidFill', {})
            if solid.get('alpha', 1) != 1 or rgb_hex(solid.get('color', {}).get('rgbColor')) != gradient['background'].upper():
                reasons.append('The gradient base background was modified.')
        except ValueError:
            reasons.append('The gradient base background is unreadable.')
    return {'supported': not reasons, 'reasons': reasons, 'texts': texts, 'band': band, 'gradient': gradient}


def style_capability(page):
    inspected = inspect_slide(page)
    # Expose the actual formatting so a reread can verify an uncertain write.
    return {'supported': inspected['supported'], 'unsupported_reasons': inspected['reasons'],
            'gradient': bool(inspected['gradient']),
            'gradient_color': (inspected['gradient'] or {}).get('gradient_color'),
            'background_fill': page.get('pageProperties', {}).get('pageBackgroundFill'),
            'cover_band_fill': (inspected['band'] or {}).get('shape', {}).get('shapeProperties', {}).get('shapeBackgroundFill'),
            'text_styles': [{'element_id': e['objectId'], 'runs': [
                {key: entry['textRun'].get('style', {}).get(key)
                 for key in ('fontFamily', 'foregroundColor')}
                for entry in e['shape']['text']['textElements'] if 'textRun' in entry]}
                for e in inspected['texts']]}


def rgb_hex(value):
    if not isinstance(value, dict):
        raise ValueError('Missing explicit RGB color')
    channels = [value.get(key, 0) for key in ('red', 'green', 'blue')]
    if any(not isinstance(c, (int, float)) or not 0 <= c <= 1 for c in channels):
        raise ValueError('Invalid RGB color')
    return '#' + ''.join(f'{round(c * 255):02X}' for c in channels)


def validate_slide_colors(page, inspected, changes):
    """Check effective colors without replacing unrequested formatting."""
    from .preferences import validate_background_contrast

    if not any(key in changes for key in (*BACKGROUND_FIELDS, 'title_color', 'body_color')):
        return
    if 'background' in changes:
        background = changes['background']
    else:
        fill = (inspected['band']['shape'].get('shapeProperties', {}).get('shapeBackgroundFill', {})
                if inspected['band'] else page.get('pageProperties', {}).get('pageBackgroundFill', {}))
        solid = fill.get('solidFill', {})
        if solid.get('alpha', 1) != 1:
            raise ValueError('Cannot validate a transparent background.')
        background = rgb_hex(solid.get('color', {}).get('rgbColor'))
    for element in inspected['texts']:
        key = color_role(element['objectId']) + '_color'
        if not any(k in changes for k in BACKGROUND_FIELDS) and key not in changes:
            continue
        for entry in element['shape']['text']['textElements']:
            run = entry.get('textRun', {})
            if not run.get('content', '').strip():
                continue
            color = changes.get(key)
            if color is None:
                color = rgb_hex(run.get('style', {}).get('foregroundColor', {}).get('opaqueColor', {}).get('rgbColor'))
            enabled, accent = effective_gradient(inspected, changes)
            validate_background_contrast(background, color, enabled, accent)


def effective_gradient(inspected, changes):
    enabled = changes.get('gradient', bool(inspected['gradient']) or 'gradient_color' in changes)
    accent = changes.get('gradient_color', (inspected['gradient'] or {}).get('gradient_color', '#93B4E8'))
    return enabled and inspected['band'] is None, accent


def apply_style(creds, presentation_id, expected_revision_id, settings, *, publish_gradient=None):
    from .editing import EditError, read_deck

    service, raw, deck = read_deck(creds, presentation_id)
    if not deck['revision_id'] or deck['revision_id'] != expected_revision_id:
        raise EditError('The deck changed or its revision is unavailable. Read it again before changing the style.')
    changes = settings.model_dump(exclude_unset=True)
    revision_id = expected_revision_id
    requests, applied, skipped = [], [], []
    for page in raw.get('slides', []):
        inspected = inspect_slide(page)
        slide_id = page['objectId']
        if not inspected['supported']:
            skipped.append({'slide_id': slide_id, 'reasons': inspected['reasons']})
            continue
        # A cover has no body text, so a body-color-only change does not affect it.
        if (inspected['band'] is not None and set(changes).issubset({'gradient', 'gradient_color'})):
            continue
        if not any(k in changes for k in BACKGROUND_FIELDS) and 'font_family' not in changes and not any(
                color_role(element['objectId']) + '_color' in changes for element in inspected['texts']):
            continue
        try:
            validate_slide_colors(page, inspected, changes)
        except (ValueError, TypeError, KeyError) as exc:
            skipped.append({'slide_id': slide_id, 'reasons': [str(exc)]})
            continue
        if 'background' in changes:
            fill = {'solidFill': {'color': {'rgbColor': rgb(changes['background'][1:])}, 'alpha': 1}}
            requests.append({'updatePageProperties': {'objectId': slide_id,
                'pageProperties': {'pageBackgroundFill': fill}, 'fields': 'pageBackgroundFill'}})
            if inspected['band']:
                requests.append({'updateShapeProperties': {'objectId': inspected['band']['objectId'],
                    'shapeProperties': {'shapeBackgroundFill': fill}, 'fields': 'shapeBackgroundFill'}})
        if inspected['band'] is None and any(k in changes for k in BACKGROUND_FIELDS):
            enabled, accent = effective_gradient(inspected, changes)
            suffix = slide_id.rsplit('_', 1)[-1]
            if inspected['gradient']:
                requests.append({'deleteObject': {'objectId': f'mvp_gradient_{suffix}'}})
            if enabled:
                background = changes.get('background') or rgb_hex(page['pageProperties']['pageBackgroundFill']['solidFill']['color']['rgbColor'])
                url = publish_gradient(background, accent)
                requests.extend(gradients.requests(suffix, background, accent, url))
        for element in inspected['texts']:
            style = {}
            if 'font_family' in changes:
                style['fontFamily'] = changes['font_family']
            key = color_role(element['objectId']) + '_color'
            if key in changes:
                style['foregroundColor'] = {'opaqueColor': {'rgbColor': rgb(changes[key][1:])}}
            if style:
                requests.append({'updateTextStyle': {'objectId': element['objectId'],
                    'textRange': {'type': 'ALL'}, 'style': style, 'fields': ','.join(style)}})
        applied.append(slide_id)
    if requests:
        try:
            response = service.presentations().batchUpdate(presentationId=presentation_id, body={
                'requests': requests, 'writeControl': {'requiredRevisionId': expected_revision_id}}).execute(num_retries=0)
            revision_id = response.get('writeControl', {}).get('requiredRevisionId')
        except HttpError as exc:
            if exc.resp.status in (400, 409, 412):
                raise EditError('Google rejected the style update; the revision may have changed or expired. Read the deck again before retrying.') from None
            raise EditError('The style update could not be confirmed. Read the deck before retrying; do not assume nothing changed.') from None
        except Exception:
            raise EditError('The style update could not be confirmed. Read the deck before retrying; do not assume nothing changed.') from None
    return {'presentation_id': presentation_id, 'presentation_url': deck['presentation_url'],
            'status': 'applied' if applied else 'unsupported', 'style_changes': changes, 'revision_id': revision_id,
            'changes': [{'slide_id': slide_id, 'style': changes} for slide_id in applied],
            'warnings': [f"{item['slide_id']}: {'; '.join(item['reasons'])}" for item in skipped],
            'applied_slide_ids': applied, 'skipped_slides': skipped,
            'limitations': ['Slides with unsupported elements are skipped entirely to avoid mismatched text/background contrast.',
                            'Text, font sizes, emphasis, bullets, layout, slide order and the cover image are preserved.',
                            'The existing cover image is not regenerated or recolored.']}
