"""Apply validated defaults to recognized slides without rebuilding their content."""
import re

from googleapiclient.errors import HttpError

from .slides import rgb


def inspect_slide(page):
    # Reuse the conservative text checks; never flatten custom or mixed text.
    from .editing import normalize_element

    slide_id = page['objectId']
    match = re.fullmatch(r'mvp_slide_(\d+)', slide_id)
    reasons, texts = [], []
    band = None
    if not match:
        reasons.append('Only slides generated by this tool support default styling.')
    suffix = match[1] if match else None
    elements = page.get('pageElements', [])
    for element in elements:
        element_id = element['objectId']
        if suffix == '0' and element_id == 'mvp_cover_image' and 'image' in element:
            continue
        if (suffix == '0' and element_id == 'mvp_cover_band'
                and element.get('shape', {}).get('shapeType') == 'TEXT_BOX'
                and all('autoText' not in entry and not entry.get('textRun', {}).get('content', '').strip()
                        for entry in element['shape'].get('text', {}).get('textElements', []))):
            band = element
            continue
        normalized = normalize_element(element)
        if normalized['editable'] and element_id in (f'mvp_title_{suffix}', f'mvp_body_{suffix}'):
            texts.append(element)
        else:
            reasons.append(f'{element_id}: unsupported element; preserved unchanged.')
    if not texts:
        reasons.append('No supported text boxes.')
    if suffix == '0' and band is None:
        reasons.append('The original empty cover title band is missing or modified.')
    return {'supported': not reasons, 'reasons': reasons, 'texts': texts, 'band': band}


def style_capability(page):
    inspected = inspect_slide(page)
    # Expose the actual formatting so a reread can verify an uncertain write.
    return {'supported': inspected['supported'], 'unsupported_reasons': inspected['reasons'],
            'background_fill': page.get('pageProperties', {}).get('pageBackgroundFill'),
            'cover_band_fill': (inspected['band'] or {}).get('shape', {}).get('shapeProperties', {}).get('shapeBackgroundFill'),
            'text_styles': [{'element_id': e['objectId'], 'runs': [
                {key: entry['textRun'].get('style', {}).get(key)
                 for key in ('fontFamily', 'foregroundColor')}
                for entry in e['shape']['text']['textElements'] if 'textRun' in entry]}
                for e in inspected['texts']]}


def apply_style(creds, presentation_id, expected_revision_id, settings):
    from .editing import EditError, read_deck

    service, raw, deck = read_deck(creds, presentation_id)
    if not deck['revision_id'] or deck['revision_id'] != expected_revision_id:
        raise EditError('The deck changed or its revision is unavailable. Read it again before applying the default style.')
    palette = settings.palette()
    fill = {'solidFill': {'color': {'rgbColor': rgb(palette['background'])}, 'alpha': 1}}
    requests, applied, skipped = [], [], []
    for page in raw.get('slides', []):
        inspected = inspect_slide(page)
        slide_id = page['objectId']
        if not inspected['supported']:
            skipped.append({'slide_id': slide_id, 'reasons': inspected['reasons']})
            continue
        requests.append({'updatePageProperties': {'objectId': slide_id,
            'pageProperties': {'pageBackgroundFill': fill}, 'fields': 'pageBackgroundFill'}})
        if inspected['band']:
            requests.append({'updateShapeProperties': {'objectId': inspected['band']['objectId'],
                'shapeProperties': {'shapeBackgroundFill': fill}, 'fields': 'shapeBackgroundFill'}})
        for element in inspected['texts']:
            kind = 'title' if element['objectId'].startswith('mvp_title_') else 'body'
            requests.append({'updateTextStyle': {'objectId': element['objectId'],
                'textRange': {'type': 'ALL'}, 'style': {'fontFamily': palette['font_family'],
                    'foregroundColor': {'opaqueColor': {'rgbColor': rgb(palette[kind])}}},
                'fields': 'fontFamily,foregroundColor'}})
        applied.append(slide_id)
    if requests:
        try:
            service.presentations().batchUpdate(presentationId=presentation_id, body={
                'requests': requests, 'writeControl': {'requiredRevisionId': expected_revision_id}}).execute(num_retries=0)
        except HttpError as exc:
            if exc.resp.status in (400, 409, 412):
                raise EditError('Google rejected the style update; the revision may have changed or expired. Read the deck again before retrying.') from None
            raise EditError('The style update could not be confirmed. Read the deck before retrying; do not assume nothing changed.') from None
        except Exception:
            raise EditError('The style update could not be confirmed. Read the deck before retrying; do not assume nothing changed.') from None
    return {'presentation_id': presentation_id, 'presentation_url': deck['presentation_url'],
            'status': 'applied' if applied else 'unsupported', 'style_settings': settings.model_dump(),
            'applied_slide_ids': applied, 'skipped_slides': skipped,
            'limitations': ['Slides with unsupported elements are skipped entirely to avoid mismatched text/background contrast.',
                            'Text, font sizes, emphasis, bullets, layout, slide order and the cover image are preserved.',
                            'The existing cover image is not regenerated or recolored.']}
